Integrate tidepool PR https://github.com/tidepool-org/platform/pull/5…
mdblp/platform pull request #107
Opened 2022-03-25 15:29 UTC by yanngit

…23 to have official mongodb driver

2022-03-25 17:07 UTC, yanngit commented
DO NOT MERGE -> need to reintegrate the waitUntilStarted for mongodb that is broken here

2022-04-04 09:35 UTC, CedricPerotto reviewed
See my remark on the connection loop.

More general (and not to be treated now): 
* we don't really use the synctask package, but we have many dependencies on it. we should remove it
* the new go.uber.org/fx module is maybe a bit overkiil for our needs... We may look if we could drop it too

2022-04-04 09:35 UTC, CedricPerotto commented on store/structured/mongo/store.go
> +	}
As far as I can see, the NewStore function is blocking until we get a mongo connection. It's not the behavoiour we had until now, service should start even if mongo store is not available.

2022-04-19 12:40 UTC, CedricPerotto requested changes

2022-04-19 12:40 UTC, CedricPerotto commented on store/structured/mongo/store.go
> +					s.closingChannel <- true
We should crash the service in that case, or it will remain up without any db connection. 
```suggestion
					s.closingChannel <- true
					panic(err)
```

2022-04-19 12:40 UTC, CedricPerotto commented on service/api/api.go
> -	}
Do we want to lose the access logs ?

2022-04-19 12:40 UTC, CedricPerotto commented on service/api/api.go
> -		accessLogMiddleware,
Same here

2022-04-20 10:01 UTC, CedricPerotto approved these changes

2022-04-20 10:03 UTC, merged