PT-624 Fix dataset are not deleted when calling "DELETE"
mdblp/platform pull request #28
Opened 2019-09-05 14:58 UTC by yvon-dblg

See https://diabeloop.atlassian.net/browse/PT-624

2019-09-06 15:14 UTC, franck-fourel requested changes
the code looks good even if it requires many changes
but I do not see any test to validate the new purge parameter.

2019-09-06 16:24 UTC, yvon-dblg commented
> the code looks good even if it requires many changes
> but I do not see any test to validate the new purge parameter.

There is one: https://github.com/mdblp/platform/blob/1feaa9d55c497600c06680b2d1e986d697bc1143/data/storeDEPRECATED/mongo/mongo_test.go#L590

But since I'm not very comfortable with the go code, and to limit the number of changes, I was thinking doing them in yourloops instead.

2019-09-09 08:24 UTC, franck-fourel commented
testing it locally, I got the following error:
{
    "errors": [
        {
            "code": "internal-server-failure",
            "title": "internal server failure",
            "detail": "Internal server failure",
            "status": "500"
        }
    ],
    "meta": {
        "trace": {
            "request": "a73dec5b8b83f5eaa3add8b7df2a6e9f"
        }
    }
}

with a json malformed error
```
{"caller":{"package":"github.com/tidepool-org/platform/service/context","function":"RespondWithInternalServerFailure","file":"service/context/responder.go","line":82},"failure":[{"code":"json-malformed","title":"json is malformed","detail":"json is malformed","caller":{"package":"github.com/tidepool-org/platform/request","function":"ParseSimpleStreamObject","file":"request/parser.go","line":102}}],"level":"error","message":"unable to parse selectors","process":{"id":17284,"name":"data","version":"00+00"},"time":"2019-09-09T10:20:07.406616+02:00","tokenHash":"d8e2876e8af0389624cb854e30b0f54d","trace":{"request":"a73dec5b8b83f5eaa3add8b7df2a6e9f"}}
```
Here is the query I used:

```
curl -X DELETE \
  http://localhost:8009/v1/data_sets/5bc0fee41417a738144b272aaa9bf9ce/data \
  -H 'Content-Type: application/json' \
  -H 'x-tidepool-session-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkdXIiOjI1OTIwMDAsImV4cCI6MTU3MDYwNjAzNSwic3ZyIjoibm8iLCJ1c3IiOiI1ODg5NzM1MmU3In0.OUOj8pMUN8b3EKdxmX0UFobYQrXq3q2sVT_EHUH6wMQ' \
  -d '{
	"purge" : "true"
}'
```

2019-09-09 18:10 UTC, franck-fourel approved these changes

2019-09-09 18:12 UTC, merged