PT-903 Patch platform-data to prevent from Android bug to happen
mdblp/platform pull request #35
Opened 2020-01-15 14:18 UTC by franck-fourel

2020-01-17 13:22 UTC, franck-fourel commented
I don't like what I did but at least it works and the tests are working. 
The thing that is not convenient is the fact that we do not log the warnings in the logs in when we have a warning and skip the related data.

2020-01-20 14:39 UTC, yvon-dblg requested changes
golint warnings:
```
golint
17a18,30
> ./data/test/datum.go:83:1: comment on exported method Datum.IsValid should be of the form "IsValid ..."
> ./data/types/activity/physical/physical.go:270:1: comment on exported method Physical.IsValid should be of the form "IsValid ..."
> ./data/types/basal/automated/automated.go:76:1: comment on exported method Automated.IsValid should be of the form "IsValid ..."
> ./data/types/basal/scheduled/scheduled.go:76:1: comment on exported method Scheduled.IsValid should be of the form "IsValid ..."
> ./data/types/basal/suspend/suspend.go:73:1: comment on exported method Suspend.IsValid should be of the form "IsValid ..."
> ./data/types/basal/temporary/temporary.go:89:1: comment on exported method Temporary.IsValid should be of the form "IsValid ..."
> ./data/types/base.go:227:1: comment on exported method Base.IsValid should be of the form "IsValid ..."
> ./data/types/blood/glucose/glucose.go:27:1: comment on exported method Glucose.IsValid should be of the form "IsValid ..."
> ./data/types/blood/ketone/ketone.go:47:1: comment on exported method Ketone.IsValid should be of the form "IsValid ..."
> ./data/types/bolus/combination/combination.go:113:1: comment on exported method Combination.IsValid should be of the form "IsValid ..."
> ./data/types/bolus/extended/extended.go:81:1: comment on exported method Extended.IsValid should be of the form "IsValid ..."
> ./data/types/bolus/normal/normal.go:65:1: comment on exported method Normal.IsValid should be of the form "IsValid ..."
> ./data/types/calculator/calculator.go:105:1: comment on exported method Calculator.IsValid should be of the form "IsValid ..."
18a32,45
> ./data/types/device/alarm/alarm.go:90:1: comment on exported method Alarm.IsValid should be of the form "IsValid ..."
> ./data/types/device/calibration/calibration.go:53:1: comment on exported method Calibration.IsValid should be of the form "IsValid ..."
> ./data/types/device/prime/prime.go:74:1: comment on exported method Prime.IsValid should be of the form "IsValid ..."
> ./data/types/device/reservoirchange/reservoirchange.go:62:1: comment on exported method ReservoirChange.IsValid should be of the form "IsValid ..."
> ./data/types/device/status/status.go:116:1: comment on exported method Status.IsValid should be of the form "IsValid ..."
> ./data/types/device/timechange/timechange.go:97:1: comment on exported method TimeChange.IsValid should be of the form "IsValid ..."
> ./data/types/food/food.go:102:1: comment on exported method Food.IsValid should be of the form "IsValid ..."
> ./data/types/insulin/insulin.go:61:1: comment on exported method Insulin.IsValid should be of the form "IsValid ..."
> ./data/types/settings/cgm/cgm.go:111:1: comment on exported method CGM.IsValid should be of the form "IsValid ..."
> ./data/types/settings/pump/pump.go:151:1: comment on exported method Pump.IsValid should be of the form "IsValid ..."
> ./data/types/state/reported/reported.go:51:1: comment on exported method Reported.IsValid should be of the form "IsValid ..."
> ./data/types/test/test.go:85:1: comment on exported function ValidateWarningsWithOrigin should be of the form "ValidateWarningsWithOrigin ..."
> ./data/types/test/test.go:93:1: comment on exported function ValidateWarningsWithExpectedOrigins should be of the form "ValidateWarningsWithExpectedOrigins ..."
> ./data/types/upload/upload.go:173:1: comment on exported method Upload.IsValid should be of the form "IsValid ..."
```

Another approach may have been to convert any negative value to the positive one:
duration := uint32(duration)
But I'm not sure if there will be less code to do.



Looks good, good job.

2020-01-20 14:39 UTC, yvon-dblg commented on data/test/datum.go
> +// returns true if there is no error and no warning in the validator
`// IsValid returns true if there is no error and no warning in the validator`
golint: ./data/test/datum.go:83:1: comment on exported method Datum.IsValid should be of the form "IsValid ..."

2020-01-20 14:39 UTC, yvon-dblg commented on CHANGELOG.md
> +- PT-9.3 Patch platform-data to prevent from Android bug to happen
```suggestion
- PT-903 Patch platform-data to prevent an Android bug to happen
```

2020-01-21 08:32 UTC, yvon-dblg approved these changes

2020-01-21 09:08 UTC, merged