PT-1004: Document the api using openApi and swaggo
mdblp/platform pull request #39
Opened 2020-02-14 17:20 UTC by yvon-dblg

WIP

2020-02-24 14:57 UTC, BigFab submitted a review, later dismissed
Except for the few changes that do not relate to openapi documentation, I am fine with this. I can generate the swagger doc locally

2020-02-24 14:57 UTC, BigFab commented on doc.sh
> +#!/bin/sh -eu
Can we name this one "buildDoc.sh" ?

2020-02-24 15:34 UTC, BigFab requested changes
Can you please rename doc.sh to buildDoc.sh?

2020-02-25 10:59 UTC, yvon-dblg commented
> 
> 
> Can you please rename doc.sh to buildDoc.sh?

yes. I used this name, because for hydrophone (https://github.com/mdblp/hydrophone/blob/dblp/doc.sh) it was the one used.

Should we have something in common?
Maybe via an artifact ?

2020-02-25 11:00 UTC, yvon-dblg commented
> 
> 
> Except for the few changes that do not relate to openapi documentation, I am fine with this. I can generate the swagger doc locally

ha yes, I commit my change in the README... sorry.
I will remove it.

2020-02-25 11:56 UTC, BigFab approved these changes
LGTM. Now I understand what these "enums" thing are here for. Thanks @yvon-dblg

2020-02-25 13:55 UTC, merged