PT-1303 add new fields to PA
mdblp/platform pull request #53
Opened 2020-06-02 16:59 UTC by franck-fourel

- Add eventType and eventID
- inputTime will be added later once validated as part of https://github.com/mdblp/platform/pull/51

2020-06-03 09:02 UTC, yvon-dblg requested changes
I have one comment/question, plus this remark not fully related to this PR:
I didn't check the PR for the spec, but all examples provided the timezoneOffset only, not the timezone.
The offset can be known from the timezone, the opposite is not true. In fact, the offset is not really needed.
We should provide example with the timezone information to not breaks what we have done on this point before.

2020-06-03 09:02 UTC, yvon-dblg commented on data/types/activity/physical/physical.go
> +	// inputTime
The inputTime field is documented in commit 694e5ac1ff57b4b8d5d6e684702cf495df38d239
Why it is not implemented ?
If not needed anymore/for now, a more explicit comment is needed.

2020-06-03 09:05 UTC, franck-fourel commented on data/types/activity/physical/physical.go
> +	// inputTime
inputTime is included as common object in #51 
That's the reason why it's not there. Waiting for approval of #51 to include it.

2020-06-10 16:42 UTC, yvon-dblg requested changes
2 questions, one I think must be change.

2020-06-10 16:42 UTC, yvon-dblg commented on data/types/activity/physical/physical.go
> +	p.EventType.Validate(validator)
The documentation should mention this behavior:
eventId is mandatory when the eventType is specified.

2020-06-10 16:42 UTC, yvon-dblg commented on data/types/activity/physical/physical.go
> +		validator.String("eventId", p.EventID).Exists()
The duration should be mandatory in this case

2020-06-11 05:24 UTC, franck-fourel commented on data/types/activity/physical/physical.go
> +	p.EventType.Validate(validator)
that's correct

2020-06-11 05:24 UTC, franck-fourel commented on data/types/activity/physical/physical.go
> +		validator.String("eventId", p.EventID).Exists()
makes sense

2020-06-11 08:32 UTC, yvon-dblg approved these changes
LGTM

2020-06-15 08:49 UTC, CedricPerotto requested changes
LGTM, just typos in the doc.
@yvon-dblg ?

2020-06-15 08:49 UTC, CedricPerotto commented on docs/UpdatedData.md
> +In the below example, The 2 objects are sent in 2 separate reauests. The first object coming with the first request indicates that the physical activity is entered on the handset at 8:00am. It starts
```suggestion
In the below example, The 2 objects are sent in 2 separate requests. The first object coming with the first request indicates that the physical activity is entered on the handset at 8:00am. It starts at 8:50am for 60 minutes. The second object that is received later on as part of a second request says that the duration of the same activity has been changed to 50 minutes. This last information was entered at 10:00am. This second object will become the effective one while first one can be considered as the history of changes. The link between both is done through the common `eventId`. 
```

2020-06-15 08:49 UTC, CedricPerotto commented on docs/UpdatedData.md
> +- `eventId`: unique ID provided by the client that is used to link stop and start events. Iw we receive several objects with the same ID, the most recent one will be the effective one while the other
```suggestion
- `eventId`: unique ID provided by the client that is used to link stop and start events. If we receive several objects with the same ID, the most recent one will be the effective one while the other objects will be considered as history of changes. The duration is __mandatory__ when this field is provided.
```

2020-06-16 08:53 UTC, yvon-dblg reviewed
Still working :)

2020-06-16 08:53 UTC, yvon-dblg commented on data/types/common/eventtype.go
> +package common
Do we keep theses files ?

2020-06-17 08:21 UTC, franck-fourel commented on data/types/common/eventtype.go
> +package common
deleted as part of f6df691

2020-06-17 08:37 UTC, franck-fourel commented
@yvon-dblg  ready for final review

2020-06-17 09:37 UTC, yvon-dblg approved these changes
LGTM
@CedricPerotto ?

2020-06-17 15:04 UTC, CedricPerotto approved these changes

2020-06-17 15:04 UTC, merged