feature/ylp 1033 create metrics when write documents in both dbs
mdblp/platform pull request #87
Opened 2021-11-09 12:58 UTC by Nas84

- add promhetheus instrumentation as a middleware for http requests
- add custom metrics in store
- update changelog

2021-11-11 16:02 UTC, ydrisR requested changes

2021-11-11 16:02 UTC, ydrisR commented on data/storeDEPRECATED/mongo/mongo.go
> +var writeDataToReadStore = promauto.NewHistogramVec(prometheus.HistogramOpts{
can you rename this so we know what it is?
For example when it is called like this `writeDataToReadStore.WithLabelValues("cbg").Observe(float64(elapsed_time))` It looks like an instruction to write data to a DB...

something like `bucketDataWritesMetrics` ?

2021-11-11 16:03 UTC, ydrisR commented
Looks good, just a minor comment on metrics variables naming

2021-11-11 16:32 UTC, Nas84 commented on data/storeDEPRECATED/mongo/mongo.go
> +var writeDataToReadStore = promauto.NewHistogramVec(prometheus.HistogramOpts{
sure will add a metrics suffix

2021-11-15 09:07 UTC, ydrisR approved these changes
LGTM

2021-11-15 09:07 UTC, merged